Add 4/17 updates to builders-challenge
mozmeao/MIECO pull request #46
Opened 2023-04-18 18:21 UTC by nathan-barrett

This PR adds the updates from 4/17 for the AI Builders Challenge

[Figma](https://www.figma.com/file/hIcxtksCssGMjTB3rdoYbA/AI-Challenge?node-id=927%3A5357&t=5uHM3xrbhBhx0gos-1)

2023-04-19 02:02 UTC, reemhamz requested changes
Nice work getting this out!
Couple nits and  an accessibility concern that I recommend updating to work for screenreaders :)

2023-04-19 02:02 UTC, reemhamz commented on pages/builders-challenge/index.html
> +<section class="c-partner-section">
**Nit:** We should add some spacing between this section and the guidelines section above. Here's what it currently looks like:

<kbd>![Screenshot 2023-04-19 at 10 09 07 AM](https://user-images.githubusercontent.com/42309026/232930912-5b54340c-b4be-464f-bdf6-98ec31fc1173.png)</kbd>

2023-04-19 02:02 UTC, reemhamz commented on pages/builders-challenge/index.html
> +                        <li class="strong">3rd prize: <span class="cross-out">$10,000</span> <span class="new-amount">$20,000</span></li>
**Suggestion (blocking/accessibility):** Instead of creating the class `cross-out` to convey a `text-decoration: line-through` rule, we should look at a more accessible solution, since screen readers won't be able to read what is the crossed-out text here, and will just hear `$10,000 $20,000`.

A solution would be to instead use the semantic `<s>` tag (shown [HERE](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s)). However, since it's only semantic and not fully accessible, there is a workaround to this sort of instance mentioned in [this section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s#accessibility_concerns) of the page).

It seems this is possibly the best way to go around making this design accessible based on my research.
More details can be explained here in the blogpost shared on the MDN page: https://www.tpgi.com/short-note-on-making-your-mark-more-accessible/

2023-04-19 02:02 UTC, reemhamz commented on pages/builders-challenge/index.html
> +                <p>Update: Craig Newmark Philanthropies makes a generous donation to Responsible AI Challenge – prize amounts now <span>doubled</span><p>
**nit (non-blocking):** I think this should include "the" before "responsible ai challenge"?
```suggestion
                <p>Update: Craig Newmark Philanthropies makes a generous donation to the Responsible AI Challenge – prize amounts now <span>doubled</span><p>
```

2023-04-19 02:02 UTC, reemhamz commented on css/_builders-challenge.scss
> +                text-decoration: line-through;
**nit (blocking):** As mentioned in the HTML page, remove the `text-decoration` rule and instead add what's shown here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s#accessibility_concerns

2023-04-19 02:02 UTC, reemhamz commented on pages/builders-challenge/index.html
**Question:** In the Figma file I see a section for the Judges? Do we have that content yet to add for this page?

2023-04-19 15:10 UTC, nathan-barrett commented on css/_builders-challenge.scss
> +                text-decoration: line-through;
Thank a11y kween

2023-04-19 15:10 UTC, nathan-barrett commented on pages/builders-challenge/index.html
They didn't get contracts set up with the judges so they said to not add it to the page yet

2023-04-20 00:53 UTC, reemhamz approved these changes
r+ 🧠

2023-04-20 00:53 UTC, merged