WIP for /ai
mozmeao/MIECO pull request #60
Opened 2023-07-07 19:40 UTC by skyfallsin

Kickoff for "First Stop" project. This PR is primarily to get a staging netlify env for demos

2023-08-07 21:03 UTC, nathan-barrett requested changes
Made some comments throughout, but noticed that /ai renders just a black screen on viewports under 1024px

2023-08-07 21:03 UTC, nathan-barrett commented on css/ai.css
> +}
Protocol (the design library) already has Inter (only a few weights though) so you could 800kb if that works for you

2023-08-07 21:03 UTC, nathan-barrett commented on templates/ai/_dark_mode.html
**Question**: If this is solely a script, reason why it shouldn't be a JS file in the `scripts/` directory?

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
> +    </head>
Could this use the dark-mode.html?

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
Noticed this page doesn't inherit the base.html files that are used on the other pages, so i'd either `extend` those or update the tags in the head of this file.

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
> +                            <h4 class="question">Why this Guide?</h4>
Failed contrast test in the Firefox a11y panel

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
> +                                <div class="carousel carousel-center max-w-3xl p-4 space-x-4 rounded-box border-2 border-gray-900 shadow-md shadow-primary">
The styling of the carousel is currently cutting off one of the images - not sure if intentional or not

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
Also look at the contrast on text on this page since in a few places they aren't meeting WCAG standards

2023-08-07 21:03 UTC, nathan-barrett commented on pages/ai/index.html
> +                    <footer id='footer' class="mzp-c-footer ">
Is this section able to use the footer.html partial? Also noticed that the styling for the footer cutting text between two different columns.

2023-08-07 21:14 UTC, skyfallsin commented on css/ai.css
> +}
I'm not using protocol, so made sense to import and we do want the weight flexibility

2023-08-07 21:16 UTC, skyfallsin commented
> Made some comments throughout, but noticed that /ai renders just a black screen on viewports under 1024px

@nathan-barrett as mentioned on slack, we're not using /index.html but are proceeding with /home.html which has most of the comments fixed.

2023-08-07 21:19 UTC, nathan-barrett commented
Can we remove `index.html` from the PR if we aren't going to be using it?

2023-08-07 21:35 UTC, skyfallsin commented on templates/ai/_dark_mode.html
addressed

2023-08-14 18:08 UTC, skyfallsin commented
@nathan-barrett note netlify redirects. I've never done this one, so you might have to tweak if I didn't get it right.

2023-08-14 21:55 UTC, nathan-barrett approved these changes
r+ thanks for working through the tailwind errors

2023-08-14 21:55 UTC, merged